import streamlit as st
import os
from dotenv import load_dotenv

# Load env variables
load_dotenv()

from agents.graph import run_decision_system

st.set_page_config(page_title="Multi-Agent AI Decision System", page_icon="🤖", layout="wide")

st.title("🤖 Multi-Agent AI Decision System")
st.markdown("Enter a query and our specialized agents will research, analyze, and provide a reviewed decision entirely in-memory (no database).")

query = st.text_input("Enter your query:", placeholder="e.g., Should our company invest in quantum computing this year?")

if st.button("Generate Decision"):
    if not query.strip():
        st.warning("Please enter a query.")
    elif not os.getenv("GROQ_API_KEY"):
        st.error("Error: GROQ_API_KEY is not set in the environment. Please check your .env file.")
    else:
        with st.spinner("Agents are working on your query..."):
            try:
                # 1. Run the Multi-Agent System
                state_result = run_decision_system(query)
                
                # 2. Display Results
                st.success("Decision process complete!")
                
                col1, col2 = st.columns(2)
                
                with col1:
                    with st.expander("🔍 Research Summary", expanded=True):
                        st.markdown(state_result.get("research_output", "No research output."))
                        
                    with st.expander("⚖️ Decision", expanded=True):
                        st.markdown(state_result.get("decision_output", "No decision output."))
                
                with col2:
                    with st.expander("📊 Analysis", expanded=True):
                        st.markdown(state_result.get("analysis_output", "No analysis output."))
                        
                    with st.expander("📝 Critic Review", expanded=True):
                        st.markdown(state_result.get("critic_output", "No critic output."))
                        
            except Exception as e:
                st.error(f"An error occurred: {e}")

st.divider()
st.caption("⚠️ **Disclaimer:** All content is generated by AI. Please consult with an expert before making any important decisions based on this information.")
